gitConfig:
  pull.ff: only
  user.signingkey: 9D183F822098553E
  user.email: k3.karthic@protonmail.ch
  user.name: Karthic Kumaran
  commit.gpgsign: "true"
tasks:
  - before: >
      rm -rf /home/gitpod/.gnupg &&
      cd /home/gitpod &&
      echo $GNUGPG | base64 -d | tar --no-same-owner -xzvf - &&
      echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf &&
      cd /workspace/totp-generator-web &&
      echo $SSH_CONFIG | base64 -d > /home/gitpod/.ssh/config && 
      chmod 600 /home/gitpod/.ssh/config &&
      echo $SSH_KEY | base64 -d > /home/gitpod/.ssh/id_rsa && 
      chmod 400 /home/gitpod/.ssh/id_rsa &&
      [[ $(grep -c codeberg /workspace/totp-generator-web/.git/config) -eq "0" ]] &&
      git remote set-url --add --push origin git@github.com:k3karthic/totp-generator-web.git &&
      git remote set-url --add --push origin git@codeberg.org:k3karthic/totp-generator-web.git &&
      git remote add codeberg git@codeberg.org:k3karthic/totp-generator-web.git
